@startuml
agent "[[#consentRecorder Consent Recorder]]" as capture
agent "[[#consentRegistry Consent Registry]]" as registry
capture -down--> registry : "Access Consent (CRUDS) [[ITI-110.html ITI-110]]"

frame "Grouped Client" {
agent "Other FHIR client" as otherClient
agent "[[#consentAuthorizationClient Consent Authorization Client]]" as client 
}
agent "[[#consentAuthorizationServer Consent Authorization Server]]" as decider
frame "Grouped Server" {
agent "[[#consentEnforcementPoint Consent Enforcement Point]]" as enforcer
agent "Other FHIR server" as otherServer
}

otherClient -down-> client: "other"
client -down-> decider : "Get Consent Access Token [[ITI-108.html ITI-108]]\nIUA: Get Authorization Server Metadata [[https://profiles.ihe.net/ITI/IUA/index.html#3103-get-authorization-server-metadata-iti-103 ITI-103]]"

decider -left-> registry: "Access Consent (SR) [[ITI-110.html ITI-110]]"
client -down-> enforcer : "IUA: Incorporate Access Token [[https://profiles.ihe.net/ITI/IUA/index.html#372-incorporate-access-token-iti-72 ITI-72]]"
decider <-right- enforcer : "Introspect Consent Token [[ITI-109.html ITI-109]]\nIUA: Get Authorization Server Metadata [[https://profiles.ihe.net/ITI/IUA/index.html#3103-get-authorization-server-metadata-iti-103 ITI-103]]"
enforcer -down-> otherServer : "other"
@enduml
