# sushi-config.yaml is documented https://fshschool.org/docs/sushi/configuration/
# ───────────────────────────────────────────────────
# the id should be lowercase made up of "ihe." + {domain acronym} + "." + {profile acronym/short-name}
# e.g. ihe.iti.mhds, or ihe.iti.basicaudit
id: ihe.iti.pcf
canonical: https://profiles.ihe.net/ITI/PCF
version: 0.0.1-current
name: IHE_ITI_PCF
title: "Privacy Consent on FHIR"
description: Supports Patient Privacy Consents in HIE scope
releaseLabel: ci-build
#releaseLabel: Trial-Implementation
#date: 2022-01-02
status: draft
publisher:
  - name: IHE IT Infrastructure Technical Committee
  - url: https://www.ihe.net/ihe_domains/it_infrastructure/
  - email: iti@ihe.net
contact:
  - name: IHE IT Infrastructure Technical Committee
    telecom:
      - system: email
        value: iti@ihe.net
license:  CC-BY-4.0
# using R4B as the consent resource had a technical correction to eliminate a build error
#fhirVersion: 4.0.1
fhirVersion: 4.3.0
jurisdiction: 'http://unstats.un.org/unsd/methods/m49/m49.htm#001'
#copyright: IHE http://www.ihe.net/Governance/#Intellectual_Property
copyrightYear: 2023+

dependencies:
  us.nlm.vsac: 
    version: 0.9.0
    uri: http://fhir.org/packages/us.nlm.vsac/ImplementationGuide/us.nlm.vsac

parameters:  # see https://confluence.hl7.org/display/FHIR/Implementation+Guide+Parameters
  path-resource:
    - input/resources
    - fsh-generated/resources
    - input/examples
#  path-pages:
#    - input/pagecontent
#    - fsh-generated/includes
  show-inherited-invariants: 'false'
  usage-stats-opt-out: 'false'
  logging: progress
  shownav: 'true'
  active-tables: 'false'
  apply-contact: 'true'
  apply-jurisdiction: 'true'
  apply-publisher: 'true'
  apply-version: 'true'
  path-binary: input/binary

resources:
# list every example here with a name, description and that exampleBoolean is true; These are used to populate the artifacts page, and are needed to eliminate build warnings 
# You may delay filling out this section until you approach publication as it is merely a nice to have and eliminates build warnings -- If you do this then you will need above the autoload-resources true


pages:
# itemize here each narrative page. Include assigned section numbers when appropriate
  index.md:
    title: "1:XX Privacy Consent on FHIR Home"
    generation: markdown
  volume-1.md:
    title: "1:XX Privacy Consent on FHIR Volume 1"
    generation: markdown
  ch-P.md:
    title: "1:P. Privacy Access Policies (Informative)"
    generation: markdown
  ITI-Y1.md:
    title: "2:3.Y1 Access Consent [ITI-Y1]"
    generation: markdown
  ITI-Y2.md:
    title: "2:3.Y2 Get Access Token [ITI-Y2]"
    generation: markdown
  ITI-Y3.md:
    title: "2:3.Y3 Introspect Token [ITI-Y3]"
    generation: markdown
  ITI-Z1.md:
    title: "3:5.Z1 Basic Consent [ITI-Z1]"
    generation: markdown
  ITI-Z2.md:
    title: "3:5.Z2 Intermediate Consent [ITI-Z2]"
    generation: markdown
  ITI-Z3.md:
    title: "3:5.Z3 Advanced Consent [ITI-Z3]"
    generation: markdown
  other.md:
    title: "Changes to Other Profiles"
    generation: markdown
  download.md:
    title: "Download and analysis"
    generation: markdown
  testplan.md:
    title: "Test Plan"
    generation: markdown
  issues.md:
    title: "Open and Closed issues"
    generation: markdown
    
menu:
  PCF Home: index.html
  Volume 1:
    "Introduction" : volume-1.html
    "Actors and Transactions" : volume-1.html#actors-and-transactions
    "Actor Options" : volume-1.html#actor-options
    "Required Groupings" : volume-1.html#required-groupings
    "Overview" : volume-1.html#overview
    "Security Considerations" : volume-1.html#security-considerations
    "Cross-Profile Considerations" : volume-1.html#other-grouping
    "Appendix P. Privacy Access Policies" : ch-P.html
  Volume 2:
    "Access Consent [ITI-Y1]" : ITI-Y1.html
    "Request Consent Authorization Decision [ITI-Y2]" : ITI-Y2.html
    "Introspect Token [ITI-Y3]" : ITI-Y3.html
  Volume 3:
    "Basic Consent" : ITI-Z1.html
    "Intermediate Consent" : ITI-Z2.html
    "Advanced Consent" : ITI-Z3.html
  Artifacts: artifacts.html
  Other: 
    "Changes to Other IHE specifications" : other.html
    "Download" : download.html
    "Test Plan" : testplan.html


