# sushi-config.yaml is documented https://fshschool.org/docs/sushi/configuration/
# ───────────────────────────────────────────────────
id: ihe.iti.pcf
canonical: https://profiles.ihe.net/ITI/PCF
version: 1.0.0-resolving
name: IHE_ITI_PCF
title: "Privacy Consent on FHIR (PCF)"
description: The Privacy Consent on FHIR (PCF) Profile provides support for patient privacy consents and access control where a FHIR API is used to access Document Sharing Health Information Exchanges.
releaseLabel: ci-build
#releaseLabel: ballot
#date: 2023-05-04
status: active
publisher:
  - name: IHE IT Infrastructure Technical Committee
  - url: https://www.ihe.net/ihe_domains/it_infrastructure/
  - email: iti@ihe.net
contact:
  - name: IHE IT Infrastructure Technical Committee
    telecom:
      - system: email
        value: iti@ihe.net
license:  CC-BY-4.0
# using R4B as the consent resource had a technical correction to eliminate a build error
#fhirVersion: 4.0.1
fhirVersion: 4.3.0
jurisdiction: 'http://unstats.un.org/unsd/methods/m49/m49.htm#001'
#copyright: IHE http://www.ihe.net/Governance/#Intellectual_Property
copyrightYear: 2023+

dependencies:
  us.nlm.vsac: 
    version: 0.9.0
    uri: http://fhir.org/packages/us.nlm.vsac/ImplementationGuide/us.nlm.vsac
  ihe.iti.balp:
    id: iheitibasicaudit
    uri: https://profiles.ihe.net/ITI/BALP/ImplementationGuide/ihe.iti.balp
    version: 1.1.1

parameters:  # see https://confluence.hl7.org/display/FHIR/Implementation+Guide+Parameters
  path-resource:
    - input/resources
    - fsh-generated/resources
    - input/examples
  show-inherited-invariants: 'false'
  usage-stats-opt-out: 'false'
  logging: progress
  shownav: 'true'
  active-tables: 'false'
  apply-contact: 'true'
  apply-jurisdiction: 'true'
  apply-publisher: 'true'
  apply-version: 'true'
  path-binary: input/binary
  excludettl: 'true'

resources:
# list every example here with a name, description and that exampleBoolean is true; These are used to populate the artifacts page, and are needed to eliminate build warnings 
# You may delay filling out this section until you approach publication as it is merely a nice to have and eliminates build warnings -- If you do this then you will need above the autoload-resources true


groups:
  BasicConsent:
    name: Explicit Basic Consent
    description: Artifacts related to [Explicit Basic option](volume-1.html#15322-explicit-basic-option)
    resources:
#      - StructureDefinition/IHE.PCF.consentFoundation
      - StructureDefinition/IHE.PCF.consentBasic
      - ValueSet/BasicPurposeVS
      - Consent/ex-consent-basic-ink
      - Consent/ex-consent-basic-treat
      - Consent/ex-consent-expired-treat
      - Consent/ex-consent-basic-reject
      - DocumentReference/ex-documentreference
      - DocumentReference/ex-consent-ink
      - Binary/B-ink
      - Organization/ex-organization
      - Patient/ex-patient
      - Practitioner/ex-clerk
      - Provenance/ex-provenance-consent-basic-treat
      - Provenance/ex-provenance2-consent-basic-treat
  IntermediateConsent:
    name: Explicit Intermediate Consent
    description: Artifacts related to [Explicit Intermediate](volume-1.html#15323-explicit-intermediate-options) option
    resources:
      - StructureDefinition/IHE.PCF.consentIntermediate
      - Consent/ex-consent-intermediate-timeframe
      - Consent/ex-consent-intermediate-not-timeframe
      - Consent/ex-consent-intermediate-authoredby
      - Consent/ex-consent-intermediate-not-authoredby
      - Consent/ex-consent-intermediate-encounter
      - Consent/ex-consent-intermediate-not-encounter
      - Consent/ex-consent-intermediate-data
      - Consent/ex-consent-intermediate-not-data
      - Consent/ex-consent-intermediate-purpose
      - Consent/ex-dissent-intermediate-break-glass
      - Encounter/ex-encounter
      - Practitioner/ex-practitioner
      - Group/ex-privilegedUsers
      - Organization/ex-org-researcher
  AdvancedConsent:
    name: Explicit Advanced Consent
    description: Artifacts related to [Explicit Advanced](volume-1.html#15324-explicit-advanced-option) option
    resources:
      - StructureDefinition/IHE.PCF.consentAdvanced
      - ValueSet/AdvancedSecurityTagVS
      - Consent/ex-consent-advanced-normal
      - Consent/ex-consent-advanced-normal-restricted
      - Consent/ex-consent-advanced-normal-not-restricted
      - Consent/ex-consent-advanced-normal-focused-restricted
      - Consent/ex-consent-advanced-normal-focused-psy
      - Consent/ex-consent-advanced-normal-focused-psy-or-sdv
      - Consent/ex-consent-advanced-normal-break-glass-restricted
  SLS:
    name: Security Labeling Service resources
    description: Artifacts to support a [Security Labeling Service (SLS)](ch-P.html#SLS)
    resources:
      - ValueSet/SlsSensitivePSY
      - ValueSet/SlsSensitiveETH
      - ValueSet/SlsSensitiveETHUD
      - ValueSet/SlsSensitiveOPIOIDUD
      - ValueSet/SlsSensitiveSDV
      - ValueSet/SlsSensitiveHIV
      - Observation/ex-alcoholUse
      - Observation/ex-bloodSugar
      - Observation/ex-bloodPressure
      - Observation/ex-weight
      - Observation/ex-weight-stone




pages:
# itemize here each narrative page. Include assigned section numbers when appropriate
  index.md:
    title: "Privacy Consent on FHIR (PCF) Home"
    generation: markdown
  volume-1.md:
    title: "1:53 Privacy Consent on FHIR"
    generation: markdown
  ch-P.md:
    title: "1:Appendix P: Privacy Access Policies (Informative)"
    generation: markdown
  ITI-108.md:
    title: "2:3.108 Access Consent [ITI-108]"
    generation: markdown
  content.md:
    title: "3:5.8 Privacy Consent Patterns"
    generation: markdown
  other.md:
    title: "Changes to Other IHE Specifications"
    generation: markdown
  download.md:
    title: "Download and Analysis"
    generation: markdown
  testplan.md:
    title: "Test Plan"
    generation: markdown
  issues.md:
    title: "Significant Changes & Issues"
    generation: markdown
    
menu:
  PCF Home: index.html
  Volume 1:
    "Introduction" : volume-1.html
    "Actors and Transactions" : volume-1.html#actors-and-transactions
    "Actor Options" : volume-1.html#actor-options
    "Required Groupings" : volume-1.html#required-groupings
    "Overview" : volume-1.html#overview
    "Security Considerations" : volume-1.html#security-considerations
    "Cross-Profile Considerations" : volume-1.html#other-grouping
    "Appendix P: Privacy Access Policies" : ch-P.html
  Volume 2:
    "Access Consent [ITI-108]" : ITI-108.html
  Volume 3:
    "Consent Patterns" : content.html
  Artifacts: artifacts.html
  Other: 
    "Changes to Other IHE Specifications" : other.html
    "Updates to ITI-71" : other.html#updates-to-iti-71
    "Download" : download.html
    "Test Plan" : testplan.html


